### ISSUE TITLE
Frontend install guide - docusaurus v3, and possibly outdated?

### ISSUE THREAD

**Issue by mwalmsley** [facebookresearch/Mephisto#1082]
Hello. I'm creating some new frontend annotation components and would eventually like to contribute them back. I'm trying to follow the frontend install guide [here](https://mephisto.ai/docs/guides/how_to_contribute/frontend_development/).

@parcel/watcher@npm:2.0.4 requires the `make` command to be built, so you need the appropriate compiler. For Ubuntu, `sudo apt-get install build-essential`. Otherwise `yarn install' gives the warnings below

```
➤ YN0002: │ @docsearch/react@npm:3.2.1 [dd5dd] doesn't provide @algolia/client-search (pc284d), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ @docsearch/react@npm:3.3.2 [afcd7] doesn't provide @algolia/client-search (pf47c7), requested by @algolia/autocomplete-preset-algolia
➤ YN0002: │ @lerna/version@npm:5.6.2 doesn't provide nx (pa74bc), requested by @nrwl/devkit
➤ YN0002: │ @nrwl/devkit@npm:15.6.2 [ce2d9] doesn't provide typescript (p45a7e), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nrwl/devkit@npm:15.6.2 [dd79a] doesn't provide typescript (pa9f23), requested by @phenomnomnominal/tsquery
➤ YN0002: │ bootstrap-chat@workspace:packages/bootstrap-chat doesn't provide @babel/plugin-syntax-flow (pd8a38), requested by eslint-plugin-flowtype
➤ YN0002: │ bootstrap-chat@workspace:packages/bootstrap-chat doesn't provide @babel/plugin-transform-react-jsx (p5ecd0), requested by eslint-plugin-flowtype
➤ YN0002: │ bootstrap-chat@workspace:packages/bootstrap-chat doesn't provide @popperjs/core (p959f7), requested by bootstrap
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [5f809] doesn't provide @babel/plugin-syntax-flow (pb4d4b), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [5f809] doesn't provide @babel/plugin-transform-react-jsx (pcd979), requested by eslint-plugin-flowtype
➤ YN0002: │ global-context-store@workspace:packages/global-context-store doesn't provide @babel/plugin-syntax-flow (p07e62), requested by eslint-plugin-flowtype
➤ YN0002: │ global-context-store@workspace:packages/global-context-store doesn't provide @babel/plugin-transform-react-jsx (p189da), requested by eslint-plugin-flowtype
➤ YN0002: │ mephisto-task@workspace:packages/mephisto-task doesn't provide @babel/plugin-syntax-flow (p44827), requested by eslint-plugin-flowtype
➤ YN0002: │ mephisto-task@workspace:packages/mephisto-task doesn't provide @babel/plugin-transform-react-jsx (p81c3c), requested by eslint-plugin-flowtype
➤ YN0002: │ mephisto-task@workspace:packages/mephisto-task [5f809] doesn't provide @babel/plugin-syntax-flow (p02002), requested by eslint-plugin-flowtype
➤ YN0002: │ mephisto-task@workspace:packages/mephisto-task [5f809] doesn't provide @babel/plugin-transform-react-jsx (pbaff5), requested by eslint-plugin-flowtype
# -- important? -- 
➤ YN0060: │ web@workspace:docs/web provides react (p2728f) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ web@workspace:docs/web provides react (p43b7f) with version 18.2.0, which doesn't satisfy what @mdx-js/react requests
➤ YN0060: │ web@workspace:docs/web provides react (pebae1) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
➤ YN0060: │ web@workspace:docs/web provides react-dom (pa62dd) with version 18.2.0, which doesn't satisfy what @docusaurus/core and some of its descendants request
➤ YN0060: │ web@workspace:docs/web provides react-dom (pe0599) with version 18.2.0, which doesn't satisfy what @docusaurus/preset-classic and some of its descendants request
# ---- 
➤ YN0002: │ web@workspace:docs/web doesn't provide webpack (p5c685), requested by file-loader
➤ YN0002: │ web@workspace:docs/web doesn't provide webpack (p8d64d), requested by url-loader
```

Most seem harmless but I think the docusaurus warnings break the docs build, as described below.

With the checked-in yarn version, 3.2.4, `build-all` fails on all packages with unclear errors like the following:

```
➤ YN0000: [global-context-store]: Process started
➤ YN0000: [mephisto-task]: Process started
➤ YN0000: [mephisto-task]: Type Error: Cannot read properties of undefined (reading '/home/walml/repos/mephisto/.pnp.cjs')
➤ YN0000: [mephisto-task]:     at r3 (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:390:10587)
➤ YN0000: [mephisto-task]:     at RQe (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:390:11068)
➤ YN0000: [mephisto-task]:     at Object.Nf (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:390:11297)
➤ YN0000: [mephisto-task]:     at /home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:691:4831
➤ YN0000: [mephisto-task]:     at Object.Na (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:390:8609)
➤ YN0000: [mephisto-task]:     at Dl.findPackageLocation (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:691:4786)
➤ YN0000: [mephisto-task]:     at /home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:423:1264
➤ YN0000: [mephisto-task]:     at Function.from (<anonymous>)
➤ YN0000: [mephisto-task]:     at o0 (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:423:1008)
➤ YN0000: [mephisto-task]:     at A7 (/home/walml/repos/mephisto/.yarn/releases/yarn-3.2.4.cjs:423:1589)
```

With the yarn version recommended by the guide (and in `package.json`), 3.0.2, `build-all` works on all packages except web. For web (`yarn workspace web build`):

```
➤ YN0000: [web]: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/walml/repos/mephisto/.yarn/__virtual__/@docusaurus-core-virtual-a5e5ef88ac/0/cache/@docusaurus-core-npm-2.2.0-7ed3f550ad-ff47e6cf85.zip/node_modules/@docusaurus/core/bin/docusaurus.mjs' imported from /home/walml/repos/mephisto/docs/web/
➤ YN0000: [web]: Did you mean to import /home/walml/repos/mephisto/.yarn/__virtual__/@docusaurus-core-virtual-a5e5ef88ac/0/cache/@docusaurus-core-npm-2.2.0-7ed3f550ad-ff47e6cf85.zip/node_modules/@docusaurus/core/bin/docusaurus.mjs?
```

docusaurus had a new release *yesterday* (my bad luck!) that bumps React from 16 to 18. See [here](https://docusaurus.io/blog/releases/3.0#breaking-changes). Looking back at the `yarn install` docusaurus warning, I'm guessing that the docusaurus/React versions are not pinned somewhere and this is breaking the web dependencies.

I hope this helps.

Separately, I notice that the guide expects workspaces which aren't listed in `package.json`. `package.json` has:

```
    "packages/mephisto-task",
    "packages/mephisto-worker-addons",
    "packages/bootstrap-chat",
    "packages/global-context-store",
    "docs/web"
```
while the guide expects newer packages like `annotated`. I am expecting to play with these annotation packages so I'm keen to check if I'm installing them correctly.

Thank you for your time!

**Comment by meta-paul** [comment]
Hi @mwalmsley thank you for mentioning this, and apologies for a slow reply. Over the past months `docker-compose` has become the preferred way of deploying Mephisto (it takes up some extra RAM, but does resolve  many dependency issues with local environments, similar to what you're reporting). Right now the docs are in READMEs, and `mephisto.ai` will be updated soon as well.

Please try to run Mephisto in docker-compose with our latest code, and if you still see any problems let us know.

**Comment by meta-paul** [comment]
Update - now you can stand up locally indexed version of Mephisto documentation (that still relies on Docusaurus) as per https://mephisto.ai/docs/guides/how_to_contribute/documentation

Closing this issue as having been resolved.
