### ISSUE TITLE
bug when run parlai_chat_task_demo on mturk sandbox

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#256]
We use the latest mephisto.
This is the commend we use `python parlai_test_script.py conf=onboarding_example mephisto/architect=heroku mephisto/provider=mturk_sandbox`.  We use this commend because the commend in [quickstart](https://github.com/facebookresearch/mephisto/blob/master/docs/quickstart.md) reports error.

Then we get the following error:

>[09-21 16:32:15] p26949 {operator.py:254} ERROR - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 242, in validate_and_run_config_or_die
    provider.setup_resources_for_task_run(task_run, run_config, task_url)
  File "/home/tao/Mephisto/mephisto/providers/mturk/mturk_provider.py", line 107, in setup_resources_for_task_run
    for qualification in task_args.get("qualifications", []):
NameError: name 'task_args' is not defined
[2020-09-21 16:32:15,742][mephisto.core.operator][ERROR] - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 242, in validate_and_run_config_or_die
    provider.setup_resources_for_task_run(task_run, run_config, task_url)
  File "/home/tao/Mephisto/mephisto/providers/mturk/mturk_provider.py", line 107, in setup_resources_for_task_run
    for qualification in task_args.get("qualifications", []):
NameError: name 'task_args' is not defined
Heroku: Deleting server: tao-parlai-chat-example-6-cc11
Destroying tao-parlai-chat-example-6-cc11 (including all add-ons)... done
[09-21 16:32:23] p26949 {operator.py:352} ERROR - Ran into error while launching run: 
Traceback (most recent call last):
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 349, in validate_and_run_config
    run_config=run_config, shared_state=shared_state
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 263, in validate_and_run_config_or_die
    raise e
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 242, in validate_and_run_config_or_die
    provider.setup_resources_for_task_run(task_run, run_config, task_url)
  File "/home/tao/Mephisto/mephisto/providers/mturk/mturk_provider.py", line 107, in setup_resources_for_task_run
    for qualification in task_args.get("qualifications", []):
NameError: name 'task_args' is not defined
[2020-09-21 16:32:23,377][mephisto.core.operator][ERROR] - Ran into error while launching run: 
Traceback (most recent call last):
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 349, in validate_and_run_config
    run_config=run_config, shared_state=shared_state
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 263, in validate_and_run_config_or_die
    raise e
  File "/home/tao/Mephisto/mephisto/core/operator.py", line 242, in validate_and_run_config_or_die
    provider.setup_resources_for_task_run(task_run, run_config, task_url)
  File "/home/tao/Mephisto/mephisto/providers/mturk/mturk_provider.py", line 107, in setup_resources_for_task_run
    for qualification in task_args.get("qualifications", []):
NameError: name 'task_args' is not defined
[09-21 16:32:23] p26949 {operator.py:302}  INFO - operator shutting down
[2020-09-21 16:32:23,378][mephisto.core.operator][INFO] - operator shutting down

It looks like `task_args` is not defined at [mturk_provider.py](https://github.com/facebookresearch/Mephisto/blob/master/mephisto/providers/mturk/mturk_provider.py).

**Comment by JackUrb** [comment]
Ah sorry for this! Let me push a quick fix for this. There are still a few kinks to work out from the hydra refactor, thanks for flagging!

**Comment by JackUrb** [comment]
Fixed in #257
