### ISSUE TITLE
Some examples don't run with newer versions of NPM

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/Mephisto#375]
The cause of this issue is `npm install` failing for versions of npm@v7. See output below.

See the Peer Dependencies section here: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

This causes npm install to fail in certain cases. For example:

### Potential Fixes

- Replace all uses of `npm install` with `npm install --legacy-peer-deps` across the different builders/architects.
- Update [the versions for peer dependencies in the package.json](https://github.com/facebookresearch/Mephisto/blob/master/packages/mephisto-task/package.json#L39-L40) in the mephisto-task pkg by prefixing with ^ to be more lenient

### Output

```console
$ cd mephisto/examples/simple_static_task && python static_test_script.py
[2021-01-27 04:42:55,653][mephisto.operations.operator][INFO] - Creating a task run under task name: html-static-task-example

added 123 packages, and audited 124 packages in 8s

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
[2021-01-27 04:43:03,347][sh.command][INFO] - <Command '/bin/rm -rf /mephisto/data/data/runs/NO_PROJECT/1/build/router', pid 19>: process started
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mephisto-task-compiler@1.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.5.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from mephisto-task@1.0.14
npm ERR! node_modules/mephisto-task
npm ERR!   mephisto-task@"^1.0.14" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-27T04_43_04_367Z-debug.log
[2021-01-27 04:43:04,386][mephisto.operations.operator][ERROR] - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/mephisto/mephisto/operations/operator.py", line 210, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/mephisto/mephisto/abstractions/architects/local_architect.py", line 132, in prepare
    self.server_dir = build_router(self.build_dir, self.task_run)
  File "/mephisto/mephisto/abstractions/architects/router/build_router.py", line 89, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 62, in build_in_dir
    self.rebuild_core()
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 45, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.
[2021-01-27 04:43:04,389][mephisto.operations.operator][ERROR] - Could not shut down architect: shutdown called before deploy
Traceback (most recent call last):
  File "/mephisto/mephisto/operations/operator.py", line 210, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/mephisto/mephisto/abstractions/architects/local_architect.py", line 132, in prepare
    self.server_dir = build_router(self.build_dir, self.task_run)
  File "/mephisto/mephisto/abstractions/architects/router/build_router.py", line 89, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 62, in build_in_dir
    self.rebuild_core()
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 45, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mephisto/mephisto/operations/operator.py", line 262, in validate_and_run_config_or_die
    architect.shutdown()
  File "/mephisto/mephisto/abstractions/architects/local_architect.py", line 175, in shutdown
    assert self.running_dir is not None, "shutdown called before deploy"
AssertionError: shutdown called before deploy
[2021-01-27 04:43:04,389][mephisto.operations.operator][ERROR] - Ran into error while launching run:
Traceback (most recent call last):
  File "/mephisto/mephisto/operations/operator.py", line 412, in validate_and_run_config
    return self.validate_and_run_config_or_die(
  File "/mephisto/mephisto/operations/operator.py", line 268, in validate_and_run_config_or_die
    raise e
  File "/mephisto/mephisto/operations/operator.py", line 210, in validate_and_run_config_or_die
    built_dir = architect.prepare()
  File "/mephisto/mephisto/abstractions/architects/local_architect.py", line 132, in prepare
    self.server_dir = build_router(self.build_dir, self.task_run)
  File "/mephisto/mephisto/abstractions/architects/router/build_router.py", line 89, in build_router
    task_builder.build_in_dir(local_server_directory_path)
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 62, in build_in_dir
    self.rebuild_core()
  File "/mephisto/mephisto/abstractions/blueprints/static_html_task/static_html_task_builder.py", line 45, in rebuild_core
    raise Exception(
Exception: please make sure npm is installed, otherwise view the above error for more info.
[2021-01-27 04:43:04,390][mephisto.operations.operator][INFO] - operator shutting down
```

**Comment by JackUrb** [comment]
What did NPM change that caused this to break? I feel like requiring the `--legacy-peer-deps` flag may be pushing us to older flows, but I'm not sure I really understand what's happened here.

**Comment by pringshia** [comment]
So as you can see via the new testing matrix here, only the node v15 (using npm@v7) cases are failing here: https://github.com/facebookresearch/Mephisto/actions/runs/515761944

The issue here is that the newer NPM version (v7) is more strict than previous versions in trying to prevent errors/issues with peer dependencies.

In our case, the mephisto-task doesn't bundle a version of react inside of it, yet claims that the installing user code should have a [peer dependency of v16.13.1](https://github.com/facebookresearch/Mephisto/blob/master/packages/mephisto-task/package.json#L39-L40).

The consuming code [specifies a react version of v16.5.2](https://github.com/facebookresearch/Mephisto/blob/master/mephisto/abstractions/blueprints/static_html_task/source/package.json#L16) which is considerably lower. This is resulting in an error with the newer stricter version of NPM.

I agree and I'm hesitant to add `--legacy-peer-deps`, I think we should fix the root cause. This means we either:
- upgrade the React requirement in the blueprint code, or
- lower the React peer requirement in the library code.

I will most likely go with option 1 above as it doesn't hurt to have code running on the newest version of React.

Side note: Ideally libraries should only be as picky as they need to be, so we can also try to figure out the minimum viable version of React to run mephisto-task with, but this will involve more rigorous testing which I don't have the bandwidth to set up at the moment. Can be slated as a future exploration/task.

**Comment by JackUrb** [comment]
I'm happy with option 1 here - I definitely agree that _ideally_ we'd have our libraries be tolerant, but going back to see when something breaks manually isn't really something I think we should invest in doing. (Building some kind of test framework for our packages though, and then automating that process alongside getting js tests though would be a different story 😉 )

**Comment by pringshia** [comment]
Yep, hoping to add some browser-based UI integration tests in the future!
