### ISSUE TITLE
Static onboarding flow fails with flask server type

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/Mephisto#476]
I was running the static HTML flow with onboarding from Mephisto's provided examples. I got this error when running with the flask server type, but not with the default node server.

The task UI loads, but form submission fails.

```
[2021-06-03 12:32:07,148][mephisto.abstractions.providers.mock.mock_unit][INFO] - Mock task launched: localhost:3000 for preview, localhost:3000/?worker_id=x&assignment_id=291 for assignment 283
[2021-06-03 12:32:27,457][mephisto.abstractions.blueprints.abstract.static_task.static_agent_state][INFO] - SAVED_DATA_TO_DISC at /private/home/rebeccaqian/Mephisto/data/data/runs/NO_PROJECT/109/onboarding/onboarding_13/agent_data.json
Unhandled exception in onboarding OnboardingAgent(13): AssertionError('Static tasks should only have final act')
Traceback (most recent call last):
  File "/private/home/rebeccaqian/Mephisto/mephisto/abstractions/blueprint.py", line 176, in launch_onboarding
    self.run_onboarding(onboarding_agent)
  File "/private/home/rebeccaqian/Mephisto/mephisto/abstractions/blueprints/abstract/static_task/static_task_runner.py", line 63, in run_onboarding
    agent_act = agent.act(timeout=self.assignment_duration_in_seconds)
  File "/private/home/rebeccaqian/Mephisto/mephisto/data_model/agent.py", line 523, in act
    self.state.update_data(act)
  File "/private/home/rebeccaqian/Mephisto/mephisto/abstractions/blueprints/abstract/static_task/static_agent_state.py", line 100, in update_data
    ), "Static tasks should only have final act"
AssertionError: Static tasks should only have final act
[2021-06-03 12:32:36,730][mephisto.operations.supervisor][INFO] - Onboarding agent onboarding_13 disconnected or errored, final status onboarding.
[2021-06-03 12:32:37,130][mephisto.operations.operator][INFO] - Operator running task ID = 109
```

Full trace available at Internal paste: P419933290

The command I used to run:
```
python static_run_with_onboarding.py mephisto.architect.server_type=flask mephisto/architect=local
```

**Comment by JackUrb** [comment]
This should be resolved by #655, to be included in the 1.0 release!
