### ISSUE TITLE
Unable to quickstart Mephisto 

### ISSUE THREAD

**Issue by kazanture** [facebookresearch/Mephisto#491]
Followed the instructions on the readme.
Both tried docker and non-docker versions both with latest release and latest master.

I keep getting this error:

```
Merge error: BlueprintArgs is not a subclass of StaticHTMLBlueprintArgs
```

Full trace:
```
(base) emre@emre-laptop:~/Mephisto/examples/simple_static_task$ python static_test_script.py
static_test_script.py:42: UserWarning: 
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main(config_name="scriptconfig")
/home/emre/anaconda3/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/provider/mock': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/home/emre/anaconda3/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/architect/local': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
/home/emre/anaconda3/lib/python3.8/site-packages/hydra/core/default_element.py:122: UserWarning: In 'mephisto/blueprint/static_task': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  warnings.warn(
Traceback (most recent call last):
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 517, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 438, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 436, in merge_with
    self._merge_with(*others)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 460, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 343, in _map_merge
    dest_node._merge_with(src_value)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 460, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 313, in _map_merge
    dest_node._validate_merge(value=src_node)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 241, in _validate_merge
    raise ValidationError(msg)
omegaconf.errors.ValidationError: Merge error: BlueprintArgs is not a subclass of StaticHTMLBlueprintArgs. value: {'_blueprint_type': '???', 'onboarding_qualification': '???', 'block_qualification': '???'}
    full_key: 
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "static_test_script.py", line 52, in <module>
    main()
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 87, in run
    cfg = self.compose_config(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 564, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 146, in load_configuration
    return self._load_configuration_impl(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 249, in _load_configuration_impl
    cfg = self._compose_config_from_defaults_list(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 519, in _compose_config_from_defaults_list
    raise ConfigCompositionException(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 517, in _compose_config_from_defaults_list
    cfg.merge_with(loaded.config)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 438, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 436, in merge_with
    self._merge_with(*others)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 460, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 343, in _map_merge
    dest_node._merge_with(src_value)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 460, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 313, in _map_merge
    dest_node._validate_merge(value=src_node)
  File "/home/emre/anaconda3/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 241, in _validate_merge
    raise ValidationError(msg)
hydra.errors.ConfigCompositionException: In 'scriptconfig': Validation error while composing config:
Merge error: BlueprintArgs is not a subclass of StaticHTMLBlueprintArgs. value: {'_blueprint_type': '???', 'onboarding_qualification': '???', 'block_qualification': '???'}
    full_key: 
    object_type=dict

```

Any idea?

**Comment by JackUrb** [comment]
I believe this is a duplicate of #488, Hydra pushed a breaking change. I'm working to resolve next week, but for now downgrading hydra to 1.0.x should be sufficient

**Comment by kazanture** [comment]
Thanks @JackUrb , downgrading hydra to 1.0.0 solved my issue. Given this is a duplicate; closing.
