### ISSUE TITLE
How to deal with 'ConnectionRefusedError: Was not able to establish a connection with the server'

### ISSUE THREAD

**Issue by SYSU-lulc** [facebookresearch/Mephisto#520]
When I ran the command 
`python run.py mephisto/architect=heroku mephisto.provider.requester_name=xxxx_sandbox`, 
it was OK at the first few times. AMT webpage could be displayed normally.

But it went wrong after I tried several times using the same command.
Part of the information is displayed like this.
`[2021-08-19 15:03:56,644][mephisto.operations.supervisor][INFO] - Sending alive
[2021-08-19 15:03:56,944][mephisto.operations.supervisor][INFO] - Sending alive
[2021-08-19 15:03:57,245][mephisto.operations.supervisor][INFO] - Sending alive
[2021-08-19 15:05:59,063][mephisto.operations.operator][ERROR] - Encountered error while launching run, shutting down
Traceback (most recent call last):
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 256, in validate_and_run_config_or_die
    architect, task_runner, provider, existing_qualifications
  File "/data4/ben/util/Mephisto/mephisto/operations/supervisor.py", line 160, in register_job
    channel_id = self.register_channel(channel, job)
  File "/data4/ben/util/Mephisto/mephisto/operations/supervisor.py", line 179, in register_channel
    "Was not able to establish a connection with the server, "
ConnectionRefusedError: Was not able to establish a connection with the server, please try to run again. If that fails,please ensure that your local device has the correct SSL certs installed.
Heroku: Deleting server: model-chat-374-681c33
Destroying model-chat-374-681c33 (including all add-ons)... done
[2021-08-19 15:06:05,012][mephisto.operations.operator][ERROR] - Ran into error while launching run: 
Traceback (most recent call last):
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 425, in validate_and_run_config
    run_config=run_config, shared_state=shared_state
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 271, in validate_and_run_config_or_die
    raise e
  File "/data4/ben/util/Mephisto/mephisto/operations/operator.py", line 256, in validate_and_run_config_or_die
    architect, task_runner, provider, existing_qualifications
  File "/data4/ben/util/Mephisto/mephisto/operations/supervisor.py", line 160, in register_job
    channel_id = self.register_channel(channel, job)
  File "/data4/ben/util/Mephisto/mephisto/operations/supervisor.py", line 179, in register_channel
    "Was not able to establish a connection with the server, "
ConnectionRefusedError: Was not able to establish a connection with the server, please try to run again. If that fails,please ensure that your local device has the correct SSL certs installed.
[2021-08-19 15:06:05,014][mephisto.operations.operator][INFO] - operator shutting down
[2021-08-19 15:06:05,015][mephisto.operations.supervisor][DEBUG] - Closing channels ['heroku_channel_model_chat_374_0']
[2021-08-19 15:06:05,015][mephisto.operations.supervisor][DEBUG] - Joining send thread
[2021-08-19 15:06:05,015][mephisto.operations.supervisor][DEBUG] - Joining agents {}`

Could you tell me how to deal with this problem?
Thank you for your attention!

**Comment by JackUrb** [comment]
Hi @SYSU-lulc - I should update this error message as we're now more familiar with the cause. This tends to occur when a Heroku server takes longer than expected to open its sockets. Retrying sometimes resolves, but ultimately we should be extending this timeout. Will put out a fix sometime soon.

**Comment by SYSU-lulc** [comment]
Hi @JackUrb - I tried many times but retrying could not resolve. So I can only expect the bug to be fixed as soon as possible. Please remember to fix it. Thank you!

**Comment by JackUrb** [comment]
If even after retry you're still having issue, I'll need you to try a few things to diagnose the cause as I cannot reproduce.

You can replace `START_DEATH_TIME` here with something much longer:
https://github.com/facebookresearch/Mephisto/blob/9e0c04f962dce88083abb42bcba81a661d68df6b/mephisto/operations/supervisor.py#L175

And then it would be worthwhile to get the full logs with an attempt with that change and using the command line option `mephisto.log_level=debug`.

**Comment by xksteven** [comment]
I ran into something similar recently.  I had to go into heroku website and manually close the running instance which fixed the issue for me.

**Comment by its-rav** [comment]
Just get this recently, no instances running from Heroku. Any updates on this guys?

**Comment by JackUrb** [comment]
@its-rav It's likely you're running into the same issue as #1024, follow along there.
