### ISSUE TITLE
NameError: name 'Unit' is not defined

### ISSUE THREAD

**Issue by yohanjo** [facebookresearch/Mephisto#596]
Hello. I ran the tasks in the quickstart instructions. While checking the results using `examine_results.py`, I get the following error message:
```
Do you want to (r)eview, or (e)xamine data? Default examine. Can put e <end> or e <start> <end> to choose how many to view
e
Input task name: html-static-task-example
Unexpected error formatting data for SandboxMTurkUnit(7, 3KWGG5KP7Q7Z65A91SDT7182L5ACM4, completed): name 'Unit' is not defined
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
Error formatting data, see above...
Unexpected error formatting data for SandboxMTurkUnit(5, 3OND0WXMI3KSBPTC6M3B5K09PVOEHQ, completed): name 'Unit' is not defined
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
Error formatting data, see above...
Unexpected error formatting data for MockUnit(3, completed): name 'Unit' is not defined
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
Error formatting data, see above...
Unexpected error formatting data for MockUnit(2, completed): name 'Unit' is not defined
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
Error formatting data, see above...
Unexpected error formatting data for MockUnit(1, completed): name 'Unit' is not defined
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
Error formatting data, see above...
```

Similarly, when I attempt to review instead, I get the following error message:
```
Do you want to (r)eview, or (e)xamine data? Default examine. Can put e <end> or e <start> <end> to choose how many to view
r
Input task name: html-static-task-example
If you'd like to soft-block workers, you'll need a block qualification. Leave blank otherwise.
Enter block qualification:
If you'd like to qualify high-quality workers, you'll need an approve qualification. Leave blank otherwise.
Enter approve qualification:
Starting review with following params:
Task name: html-static-task-example
Blocking qualification: None
Approve qualification: None
Press enter to continue...
You will be reviewing actual tasks with this flow. Tasks that you either Accept or Pass will be paid out to the worker, while rejected tasks will not. Passed tasks will be specially marked such that you can leave them out of your dataset.
You may enter the option in caps to apply it to the rest of the units for a given worker.
**************
You should only reject tasks when it is clear the worker has acted in bad faith, and didn't actually do the task. Prefer to pass on tasks that were misunderstandings.
**************

WARNING:root:Direct Worker and data model access via ...Worker(db, id) is now deprecated in favor of calling Worker.get(db, id). Please update callsites, as we'll remove this compatibility in the 1.0 release, targetting October 2021
Reviewing for worker x, (1/2), Previous (First time worker!) (total remaining: 5)
Traceback (most recent call last):
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 48, in <module>
    main()
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 44, in main
    run_examine_or_review(db, format_for_printing_data)
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 279, in run_examine_or_review
    run_examine_by_worker(db, format_data_for_printing)
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 223, in run_examine_by_worker
    print(format_data_for_printing(data_browser.get_data_from_unit(unit)))
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 33, in format_for_printing_data
    file_dir = Unit.get(db, data["unit_id"]).get_assigned_agent().get_data_dir()
NameError: name 'Unit' is not defined
```

**Comment by JackUrb** [comment]
Hi @yohanjo, this should be resolved as of #601, sorry for the disruption!
