### ISSUE TITLE
KeyError: 'times'

### ISSUE THREAD

**Issue by yohanjo** [facebookresearch/Mephisto#597]
Hello. I ran the parlai chat example and tried to see the results using `examine_results.py`. I get the following error message:
```
Do you want to (r)eview, or (e)xamine data? Default examine. Can put e <end> or e <start> <end> to choose how many to view

Input task name: parlai-chat-example
Unexpected error formatting data for SandboxMTurkUnit(16, 3UDTAB6HID405TWZ03G47E0HCH8092, completed): 'times'
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 21, in format_for_printing_data
    duration = contents["times"]["task_end"] - contents["times"]["task_start"]
KeyError: 'times'
Error formatting data, see above...
Unexpected error formatting data for MockUnit(11, completed): 'times'
Traceback (most recent call last):
  File ".../Mephisto/mephisto/tools/examine_utils.py", line 36, in _get_and_format_data
    formatted = format_data_for_printing(data)
  File ".../Mephisto/examples/simple_static_task/examine_results.py", line 21, in format_for_printing_data
    duration = contents["times"]["task_end"] - contents["times"]["task_start"]
KeyError: 'times'
Error formatting data, see above...
```

**Comment by JackUrb** [comment]
Hi @yohanjo - the examine script as currently written isn't set up for showing `parlai_chat` tasks. Here's a rought snippet from a project I'm using elsewhere, though it doesn't distinguish which worker is which here:
```
def format_data_for_printing(data):
    messages = data['data']['messages']

    def format_message(message):
        return f"{message['id']}: {message['text']}"

    formatted_messages = [format_message(m) for m in messages]
    message_text = "\n".join(formatted_messages)
    return message_text
```
