### ISSUE TITLE
Error: This URL must use the HTTPS protocol

### ISSUE THREAD

**Issue by claudiogreco** [facebookresearch/Mephisto#695]
Hello,

I would need to launch an app built using Mephisto on a local server interfacing it with Amazon Mechanical Turk. In ordered to do that, I registered a sandbox with the "mephisto register" command and I set the following configuration:
```
defaults = [
    {'mephisto/blueprint': STATIC_BLUEPRINT_TYPE},
    {"mephisto/architect": "local"},
    {"mephisto/provider": "mturk_sandbox"},
    {"conf": "example_local"},
]
```

Unfortunately, when I launch the app I obtain the following error:
```
Traceback (most recent call last):
  File "/home/cg2029/miniconda3/envs/en-trust/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/cg2029/miniconda3/envs/en-trust/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cg2029/en-trust-explore/parlai/crowdsourcing/tasks/trustworthiness_annotations/src/mephisto/mephisto/operations/task_launcher.py", line 194, in _launch_limited_units
    unit.launch(url)
  File "/home/cg2029/en-trust-explore/parlai/crowdsourcing/tasks/trustworthiness_annotations/src/mephisto/mephisto/abstractions/providers/mturk/mturk_unit.py", line 261, in launch
    client, frame_height, task_url, hit_type_id
  File "/home/cg2029/en-trust-explore/parlai/crowdsourcing/tasks/trustworthiness_annotations/src/mephisto/mephisto/abstractions/providers/mturk/mturk_utils.py", line 469, in create_hit_with_hit_type
    Question=question_data_struture,
  File "/home/cg2029/miniconda3/envs/en-trust/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cg2029/miniconda3/envs/en-trust/lib/p```ython3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ParameterValidationError) when calling the CreateHITWithHITType operation: The value "localhost:3000" is not valid for the parameter ExternalURL. This URL must use the HTTPS protocol.. (1646761383593 s)
``````

Could you please help me?

Thank you in advance for your attention.

Kind regards,
Claudio

**Comment by JackUrb** [comment]
Hi Claudio - MTurk requires secured URLs to be able to host tasks on MTurk. If you had your own externally accessible server and already owned a URL w/ certificates, you could consider the notes in #409. More likely though, for a public launch you'll want to use the `HerokuArchitect` (`"mephisto/architect": "heroku"`).

**Comment by JackUrb** [comment]
Closing due to inactivity. Please feel to reopen if you're still having issues, or have other questions!
