### ISSUE TITLE
Mephisto CLI and ParlAI Error

### ISSUE THREAD

**Issue by ncmeade** [facebookresearch/Mephisto#768]
Hi,

Thank you for the useful code!

I've found that the Mephisto CLI works well after initial installation, however, after installing `parlai (1.6.0)` in the same environment (as required by some examples such as [parlai_chat_task_demo](https://github.com/facebookresearch/Mephisto/tree/main/examples/parlai_chat_task_demo)), the Mephisto CLI doesn't work. There looks like there might be a dependency clash between `mephisto` and `parlai`.

Steps to reproduce:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ cd ~/Mephisto
$ pip3 install -e .
$ mephisto check
Mephisto seems to be set up correctly.

$ pip3 install parlai
$ mephisto check
Traceback (most recent call last):
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (websockets 10.2 (/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages), Requirement.parse('websockets==10.1'), {'mephisto'})
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/bin/mephisto", line 33, in <module>
    sys.exit(load_entry_point('mephisto', 'console_scripts', 'mephisto')())
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/bin/mephisto", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nick/Downloads/ComplexQA-Mephisto/mephisto/__init__.py", line 27, in <module>
    fill_registries()
  File "/home/nick/Downloads/ComplexQA-Mephisto/mephisto/operations/registry.py", line 119, in fill_registries
    importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nick/Downloads/ComplexQA-Mephisto/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_blueprint.py", line 22, in <module>
    from mephisto.abstractions.blueprints.parlai_chat.parlai_chat_task_runner import (
  File "/home/nick/Downloads/ComplexQA-Mephisto/mephisto/abstractions/blueprints/parlai_chat/parlai_chat_task_runner.py", line 12, in <module>
    from parlai.core.agents import Agent as ParlAIAgent  # type: ignore
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/parlai/core/agents.py", line 50, in <module>
    from parlai.core.opt import Opt
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/parlai/core/opt.py", line 18, in <module>
    import pkg_resources
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/nick/Downloads/ComplexQA-Mephisto/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'websockets==10.1' distribution was not found and is required by mephisto
```

Python version: 3.8.10
Operating system: Ubuntu 20.04

**Comment by JackUrb** [comment]
Thanks for the flag @ncmeade! 

@EricMichaelSmith given the number of things that have come up recently on this front, I'm going to see what options we have as far as relaxing some of the specific version number issues between Mephisto and ParlAI, and outright _dropping_ the ones that still exist in ParlAI only because they used to be used by ParlAI-MTurk

**Comment by JackUrb** [comment]
Hi @ncmeade - sorry for the delay here! Following #779 and the `v1.0.3` release our dependencies should be better aligned with ParlAI's. Once https://github.com/facebookresearch/ParlAI/pull/4677 lands over there you should be good to go in the future!
